---
- name: set hostname
  shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  ignore_errors: yes
  # hostname: name={{ inventory_hostname }}

- name: use debian mirror
  template: src={{ debian.sources_list }} dest=/etc/apt/sources.list

- name: upgrade the distro
  apt:
    update_cache: yes
    upgrade: yes

- name: install common packages
  apt:
    name: {{ packages }}
    state: latest
  vars:
    packages:
      - vim
      - curl
      - gnupg
      - rsync
      - wget
      - ack-grep
      - python-pycurl
      - apt-transport-https
      - aptitude

- name: use locales
  locale_gen: name={{ debian.locale }} state=present
